import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "AI Projects",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ fontFamily: 'Roboto Mono, Source Code Pro, Courier New, monospace' }}>
        {children}
      </body>
    </html>
  );
}
